### ISSUE TITLE
Using api() command in before hook does not work

### ISSUE THREAD

**Issue by RastoHu** [filiphric/cypress-plugin-api#20]
If I include `api()` command to before all hook, cypress returns an error: `cy.api is not a function Because this error occurred during a before all hook we are skipping the remaining tests in the current suite`. For the `request()` command it works fine. Also, I did not get this error in before each hook.
Request example:

```
describe('send request', () => {
    before(() => {
         cy.api({
             method: 'GET',
             url: 'some/url',
                 auth: {
                     bearer: 'Login Token'
                 }
             }).then(response => {
                 expect(response.status, 'Response is not an error').to.eq(200);
                 }
            })
        })
    })

    it('should do something', () => {
        //tests
    })
})
```

**Comment by filiphric** [comment]
yup, this was probably introduced by #16 where I changed how the UI is initialized. I will need to figure out a way of how to initialize the UI in some other way so that it is immune to `cy.session()` screen as well as hooks. before, initialization was tied to `Cypress.on('test:before:run')`

**Comment by mateustalles** [comment]
This one would be very handful for me because I use a lot of API calls to setup test data in the before/beforeEach hooks.

**Comment by filiphric** [comment]
good news! I finally figured out how to fix this whole issue, just need to figure out what is making my tests fail. should not be too complicated. next release is definitely going to fix this issue

**Comment by filiphric** [comment]
closed by #23
